##### Stage 1 - Create the build-image 
FROM node:14 as node
LABEL author="Alexander Pajer"
WORKDIR /app
COPY package.json package.json
RUN npm install
COPY . .
RUN npm run build -- --configuration production

##### Stage 2 - Create the run-time-image 
FROM nginx:alpine
VOLUME /var/cache/nginx

# Take from node-build
COPY --from=node /app/dist/config-env /usr/share/nginx/html
# Take from project folder
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

# docker build --rm -f "dockerfile" -t config-env .
# docker run -d --rm -p 5052:80 config-env
# http://localhost:5052/

# Publish Image to dockerhub
# docker tag foodui arambazamba/config-env
# docker push arambazamba/config-env