##### Stage 1 - Create the build-image -> SDK, more vulnerabel, größer
FROM node:14 as node
LABEL author="Alexander Pajer"
WORKDIR /app
COPY package.json package.json
RUN npm install
COPY . .
RUN npm run build -- --configuration production

##### Stage 2 - Create the run-time-image  -> kein SDK, less vulnerabel (less tool), klein
FROM nginx:alpine
VOLUME /var/cache/nginx

# Take from node-build
COPY --from=node /app/dist/food-ui /usr/share/nginx/html 
# Take from project folder
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/env.transform.js > /usr/share/nginx/html/assets/env.js && exec nginx -g 'daemon off;'"]

# docker build --rm -f "dockerfile" -t foodui-auth .
# docker run -d --rm -p 5052:80 foodui-auth 
# docker run -d --rm -p 5052:80 foodui-auth --env apiUrl="https://food-api-staging-4591.azurewebsites.net" applicationInsights=""
# http://localhost:5052/

# Publish Image to dockerhub
# docker tag foodui arambazamba/foodui-auth
# docker push arambazamba/foodui-auth